name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The url for the cypress test'
        required: false

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Check url
        run: echo "${{ inputs.url }}"
      - name: Cypress run
        run: npm run cypress:run
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE: ${secrets.NOTION_DATABASE}
          TEST_URL: ${{ inputs.url }}